---
apiVersion: batch/v1
kind: Job
metadata:
  name: ship-data-loader
  namespace: ship-detect
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: loader
        image: python:3.9-slim
        volumeMounts:
        - name: data-vol
          mountPath: /mnt/data
        command: ["/bin/bash", "-c"]
        args:
        - |
          set -e

          # 1) Install needed packages
          pip install --no-cache-dir kagglehub pyyaml
          export KAGGLE_USERNAME="mattwmorris"
          export KAGGLE_KEY="fba82e30865d8bb52e3ccedcc6da345e"

          # 2) Download dataset from Kaggle
          python -c "import kagglehub; kagglehub.dataset_download('vinayakshanawad/ships-dataset')"

          # 3) Copy raw YOLO data into /mnt/data
          DS_PATH="/root/.cache/kagglehub/datasets/vinayakshanawad/ships-dataset/versions/1"
          cp -r "$DS_PATH/Ships dataset/train" /mnt/data/train
          cp -r "$DS_PATH/Ships dataset/valid" /mnt/data/valid
          cp "$DS_PATH/Ships dataset/data.yaml" /mnt/data/data.yaml
          # 4) Create reorganizing script
          apt-get update
          apt-get install -y git
          git clone https://github.com/mm-rafay/image-class
          cd image-class/
          # 5) Run reorganizing script
          chmod +x reorganize_for_imagefolder.py
          python reorganize_for_imagefolder.py

          echo "Data loaded & reorganized successfully."
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: ship-data-pvc
