apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: image-inference-hpa
  namespace: image-class
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-inference
  minReplicas: 1
  maxReplicas: 2        # since we only have 2 GPU nodes, max 2 pods (one per node)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
