apiVersion: batch/v1
kind: Job
metadata:
  name: ship-train-job
  namespace: ship-detect
spec:
  backoffLimit: 0
  template:
    spec:
      imagePullSecrets:
      - name: ecr-creds
      restartPolicy: Never
      containers:
      - name: trainer
        image: 898121064240.dkr.ecr.us-east-1.amazonaws.com/ship-train:latest
        imagePullPolicy: Always
        env:
          - name: DATA_DIR
            value: "/mnt/data"
          - name: OUTPUT_DIR
            value: "/mnt/model"
          - name: EPOCHS
            value: "5"
        volumeMounts:
          - name: dataset-vol
            mountPath: /mnt/data
          - name: model-vol
            mountPath: /mnt/model
          - name: shm
            mountPath: /dev/shm
        resources:
          limits:
            cpu: "4"
            memory: "15Gi"
            nvidia.com/gpu: 1
          requests:
            cpu: "2"
            memory: "10Gi"
            nvidia.com/gpu: 1
      volumes:
      - name: dataset-vol
        persistentVolumeClaim:
          claimName: ship-data-pvc
      - name: model-vol
        persistentVolumeClaim:
          claimName: ship-model-pvc
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 4Gi
