apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-model-pvc
  namespace: image-class
spec:
  accessModes:
    - ReadWriteOnce        # RWO; for multi-node inference, consider an RWX volume (NFS/EFS)
  resources:
    requests:
      storage: 5Gi         # storage for model files (adjust as needed)
  storageClassName: local-path
